## docker container run -p 8081:80 -it ubuntu:22.04 /bin/bash
# apt update
# apt install apache2 -y
# service apache2 start

## docker container run -p 8082:80 -it ubuntu:22.04 /bin/bash
# apt update
# apt install nginx -y
# service apache2 start

# docker commit <container-id>

## simple dockerfile
FROM alpine
CMD [ "echo", "welcome to docker" ]