services:
  app:
    image: httpd
    ports:
      - "8080:80"
  db:
    image: mysql



version: '3'
 services:
  httpd:
    image: httpd:latest
    ports: 
      - 80:80
  nginx:
    image: nginx:latest
    ports:
      - 8080:80


